### ISSUE TITLE
Failure with 2-point cloud

### ISSUE THREAD

**Issue by mankoff** [CRREL/points2grid#7] opened 2013-06-16 21:22 UTC
Given:

```
0,0,10
10,10,0
```

And processing with:

```
points2grid -i test.xyz --output_format grid -r 1E4 --input_format ascii --resolution 1E4 --output_file_name test.xyz --min --max --mean
```
The mean should be `5`, the min `0`, and the max `10`. But all values are just `0`. If the order is switched, all values are `10`. North, East, South, and West are also all reported as just the last line.

**Comment by gadomski** [comment] 2015-04-26 16:14
Years later, I am unable to reproduce this issue. The regression test will be merged with **master**, because tests are good. Closing as unable-to-reproduce.

**Closed by gadomski** 2015-04-26 16:14 UTC
